doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(DATABASE_NAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PWD)%'
        driver: 'pdo_mysql'
        charset: utf8mb4
        server_version: '5.7'
        # database_host: mysql51-115.perso
        # database_port: 3306
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
